// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Google_Gemini
{
    internal sealed partial class Vsix
    {
        public const string Id = "Google_Gemini.7f683845-9a67-475e-9f8f-c732d777db44";
        public const string Name = "Google_Gemini";
        public const string Description = @"The Google Gemini Web Extension allows you to seamlessly integrate the Gemini web interface directly within your Visual Studio Code.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Himanshu Kumar Sharma HKS";
        public const string Tags = "";
    }
}
