// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Google_Gemini
{
    internal sealed partial class Vsix
    {
        public const string Id = "Google_Gemini.63df5125-c4c2-45c4-b59f-dcba135a8ce6";
        public const string Name = "Google_Gemini";
        public const string Description = @"The Google Gemini Web Extension allows you to seamlessly integrate the ChatGPT web interface directly within your Visual Studio Code (VS Code) environment. This enables you to utilize AI assistance while coding, enhancing your productivity and creativity.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Himanshu Kumar Sharma HKS";
        public const string Tags = "";
    }
}
